apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular 
    spec:
      containers:
      - name: beta
        image: sudhirgurav24/sudhirdockerrepo:63
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31500
