apiVersion : apps/v1
kind: Deployment
metadata:
  name: sudhirhelloangular 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudhirhelloangular
  template:
    metadata:
      labels:
        app: sudhirhelloangular 
    spec:
      containers:
        - name: sudhirhelloangular 
          image: sudhirnewacr.azurecr.io/sudhirhelloangular
          ports:
          - containerPort: 3000